# Generated by Django 4.2 on 2024-07-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название направления",
                        max_length=300,
                        verbose_name="название",
                    ),
                ),
                (
                    "room",
                    models.IntegerField(
                        help_text="Укажите номер кабинета", verbose_name="кабинет"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="Имя врача",
                        max_length=100,
                        null=True,
                        verbose_name="имя",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Фамилия врача",
                        max_length=100,
                        null=True,
                        verbose_name="Фамилмя",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="image/",
                        verbose_name="изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "сотрудник",
                "verbose_name_plural": "сотрудники",
            },
        ),
    ]
