# Generated by Django 4.2 on 2024-07-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_employee_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="Имя врача",
                max_length=100,
                null=True,
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="image/", verbose_name="Фотография"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(
                help_text="Введите название направления",
                max_length=300,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="room",
            field=models.IntegerField(
                help_text="Укажите номер кабинета", verbose_name="Кабинет"
            ),
        ),
    ]
