# Generated by Django 4.2 on 2024-07-27 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employee", "0003_alter_employee_first_name_alter_employee_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="image",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="password",
        ),
        migrations.AddField(
            model_name="employee",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(
                choices=[
                    ("Therapist", "Терапевт"),
                    ("Ophthalmologist", "Офтальмолог"),
                    ("nurse", "Медсестра"),
                ],
                default=None,
                help_text="Выберите название направления",
                verbose_name="Название",
            ),
        ),
    ]
