# Generated by Django 4.2 on 2024-07-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_remove_employee_first_name_remove_employee_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="image/", verbose_name="изображение"
            ),
        ),
    ]
