# Generated by Django 4.2 on 2024-07-28 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0005_employee_photo"),
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите сотрудника",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.employee",
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(
                help_text="Введите название услуги",
                max_length=300,
                verbose_name="Название услуги",
            ),
        ),
    ]
