# Generated by Django 4.2 on 2024-08-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_signup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="time",
            field=models.CharField(
                choices=[
                    (8, "08:00"),
                    (9, "09:00"),
                    (10, "10:00"),
                    (11, "11:00"),
                    (13, "13:00"),
                    (14, "14:00"),
                    (15, "15:00"),
                    (16, "16:00"),
                ],
                help_text="Выберите время записи",
                verbose_name="время записи",
            ),
        ),
    ]
