# Generated by Django 4.2 on 2024-08-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_alter_signup_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="time",
            field=models.CharField(
                choices=[
                    ("08:00", "08:00"),
                    ("09:00", "09:00"),
                    ("10:00", "10:00"),
                    ("11:00", "11:00"),
                    ("13:00", "13:00"),
                    ("14:00", "14:00"),
                    ("15:00", "15:00"),
                    ("16:00", "16:00"),
                ],
                help_text="Выберите время записи",
                verbose_name="время записи",
            ),
        ),
    ]
