# Generated by Django 4.2 on 2024-08-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0005_alter_signup_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="date",
            field=models.DateField(help_text="ГГГГ-ММ-ДД", verbose_name="Дата записи"),
        ),
    ]
