# Generated by Django 4.2 on 2024-08-10 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0007_alter_signup_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="date",
            field=models.DateField(
                choices=[
                    (datetime.datetime(2024, 8, 10, 20, 22, 21, 465119), "Сегдня"),
                    (datetime.datetime(2024, 8, 11, 20, 22, 21, 465119), "Завра"),
                    (datetime.datetime(2024, 8, 12, 20, 22, 21, 465119), "Послезавтра"),
                ],
                help_text="Выберите дату записи",
                verbose_name="Дата записи",
            ),
        ),
    ]
