# Generated by Django 4.2 on 2024-08-10 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0008_alter_signup_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="date",
            field=models.DateField(
                choices=[
                    (
                        datetime.datetime(2024, 8, 10, 20, 23, 26, 956518),
                        datetime.datetime(2024, 8, 10, 20, 23, 26, 956518),
                    ),
                    (
                        datetime.datetime(2024, 8, 11, 20, 23, 26, 956518),
                        datetime.datetime(2024, 8, 11, 20, 23, 26, 956518),
                    ),
                    (
                        datetime.datetime(2024, 8, 12, 20, 23, 26, 956518),
                        datetime.datetime(2024, 8, 12, 20, 23, 26, 956518),
                    ),
                ],
                help_text="Выберите дату записи",
                verbose_name="Дата записи",
            ),
        ),
    ]
