# Generated by Django 4.2 on 2024-08-10 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0009_alter_signup_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="date",
            field=models.DateField(
                choices=[
                    (datetime.date(2024, 8, 10), datetime.date(2024, 8, 10)),
                    (datetime.date(2024, 8, 11), datetime.date(2024, 8, 11)),
                    (datetime.date(2024, 8, 12), datetime.date(2024, 8, 12)),
                ],
                help_text="Выберите дату записи",
                verbose_name="Дата записи",
            ),
        ),
    ]
