# Generated by Django 4.2 on 2024-08-11 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0010_alter_signup_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="signup",
            options={"verbose_name": "запись", "verbose_name_plural": "записи"},
        ),
        migrations.AlterField(
            model_name="signup",
            name="date",
            field=models.DateField(
                choices=[
                    (datetime.date(2024, 8, 11), datetime.date(2024, 8, 11)),
                    (datetime.date(2024, 8, 12), datetime.date(2024, 8, 12)),
                    (datetime.date(2024, 8, 13), datetime.date(2024, 8, 13)),
                ],
                help_text="Выберите дату записи",
                verbose_name="Дата записи",
            ),
        ),
    ]
