# Generated by Django 4.2 on 2024-08-11 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0005_employee_photo"),
        ("service", "0011_alter_signup_options_alter_signup_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Выбыерите сотрудника",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.employee",
                verbose_name="Сотрудник",
            ),
        ),
    ]
