# Generated by Django 4.2 on 2024-08-14 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0012_alter_signup_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="date",
            field=models.DateField(
                choices=[
                    (datetime.date(2024, 8, 14), datetime.date(2024, 8, 14)),
                    (datetime.date(2024, 8, 15), datetime.date(2024, 8, 15)),
                    (datetime.date(2024, 8, 16), datetime.date(2024, 8, 16)),
                ],
                help_text="Выберите дату записи",
                verbose_name="Дата записи",
            ),
        ),
        migrations.AlterField(
            model_name="signup",
            name="time",
            field=models.CharField(
                choices=[
                    (datetime.timedelta(seconds=28800), "08:00"),
                    (datetime.timedelta(seconds=32400), "09:00"),
                    (datetime.timedelta(seconds=36000), "10:00"),
                    (datetime.timedelta(seconds=39600), "11:00"),
                    (datetime.timedelta(seconds=46800), "13:00"),
                    (datetime.timedelta(seconds=50400), "14:00"),
                    (datetime.timedelta(seconds=54000), "15:00"),
                    (datetime.timedelta(seconds=57600), "16:00"),
                ],
                help_text="Выберите время записи",
                verbose_name="время записи",
            ),
        ),
    ]
