# Generated by Django 4.2 on 2024-08-14 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0015_alter_signup_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="time",
            field=models.TimeField(
                choices=[
                    (datetime.timedelta(seconds=28800), "EIGHT"),
                    (datetime.timedelta(seconds=32400), "NINE"),
                    (datetime.timedelta(seconds=36000), "TEN"),
                    (datetime.timedelta(seconds=39600), "ELEVEN"),
                    (datetime.timedelta(seconds=46800), "THIRTEEN"),
                    (datetime.timedelta(seconds=50400), "FOURTEEN"),
                    (datetime.timedelta(seconds=54000), "FIFTEEN"),
                    (datetime.timedelta(seconds=57600), "SIXTEEN"),
                ],
                help_text="Выберите время записи",
                verbose_name="время записи",
            ),
        ),
    ]
