# Generated by Django 4.2 on 2024-08-14 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0016_alter_signup_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="time",
            field=models.TimeField(
                choices=[
                    (datetime.timedelta(seconds=28800), "8:00:00"),
                    (datetime.timedelta(seconds=32400), "9:00:00"),
                    (datetime.timedelta(seconds=36000), "10:00:00"),
                    (datetime.timedelta(seconds=39600), "11:00:00"),
                    (datetime.timedelta(seconds=46800), "13:00:00"),
                    (datetime.timedelta(seconds=50400), "14:00:00"),
                    (datetime.timedelta(seconds=54000), "15:00:00"),
                    (datetime.timedelta(seconds=57600), "16:00:00"),
                ],
                help_text="Выберите время записи",
                verbose_name="время записи",
            ),
        ),
    ]
