# Generated by Django 4.2 on 2024-08-14 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0017_alter_signup_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="date",
            field=models.DateField(
                choices=[
                    (datetime.date(2024, 8, 14), datetime.date(2024, 8, 14)),
                    (datetime.date(2024, 8, 15), datetime.date(2024, 8, 15)),
                    (datetime.date(2024, 8, 15), datetime.date(2024, 8, 15)),
                ],
                help_text="Выберите дату записи",
                verbose_name="Дата записи",
            ),
        ),
        migrations.AlterField(
            model_name="signup",
            name="time",
            field=models.TimeField(
                choices=[
                    (datetime.time(8, 0), 8),
                    (datetime.time(9, 0), 9),
                    (datetime.time(10, 0), 10),
                    (datetime.time(11, 0), 11),
                    (datetime.time(13, 0), 13),
                    (datetime.time(14, 0), 14),
                    (datetime.time(15, 0), 15),
                    (datetime.time(16, 0), 16),
                ],
                help_text="Выберите время записи",
                verbose_name="время записи",
            ),
        ),
    ]
