# Generated by Django 4.2 on 2024-08-15 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0018_alter_signup_date_alter_signup_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="date",
            field=models.DateField(
                blank=True,
                choices=[
                    (datetime.date(2024, 8, 15), datetime.date(2024, 8, 15)),
                    (datetime.date(2024, 8, 16), datetime.date(2024, 8, 16)),
                    (datetime.date(2024, 8, 17), datetime.date(2024, 8, 17)),
                ],
                help_text="Выберите дату записи",
                null=True,
                verbose_name="Дата записи",
            ),
        ),
    ]
