# Generated by Django 4.2 on 2024-08-15 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0019_alter_signup_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="time",
            field=models.TimeField(
                blank=True,
                choices=[
                    (datetime.time(8, 0), 8),
                    (datetime.time(9, 0), 9),
                    (datetime.time(10, 0), 10),
                    (datetime.time(11, 0), 11),
                    (datetime.time(13, 0), 13),
                    (datetime.time(14, 0), 14),
                    (datetime.time(15, 0), 15),
                    (datetime.time(16, 0), 16),
                ],
                help_text="Выберите время записи",
                null=True,
                verbose_name="время записи",
            ),
        ),
    ]
