# Generated by Django 4.2 on 2024-08-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0020_alter_signup_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="date",
            field=models.DateField(
                blank=True,
                help_text="Выберите дату записи",
                null=True,
                verbose_name="Дата записи",
            ),
        ),
        migrations.AlterField(
            model_name="signup",
            name="time",
            field=models.TimeField(
                blank=True,
                help_text="Выберите время записи",
                null=True,
                verbose_name="время записи",
            ),
        ),
    ]
